// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class CoinClaimHandle : RemoteTableHandle<EventContext, CoinClaim>
        {
            public override string RemoteTableName => "coin_claim";

            public sealed class KeyUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CoinClaim row) => row.Key;

                public KeyUniqueIndex(CoinClaimHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(CoinClaim row) => row.RoomId;

                public RoomIdIndex(CoinClaimHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal CoinClaimHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(CoinClaim row) => row.Key;
        }

        public readonly CoinClaimHandle CoinClaim;
    }

    public sealed class CoinClaimCols
    {
        public global::SpacetimeDB.Col<CoinClaim, ulong> Key { get; }
        public global::SpacetimeDB.Col<CoinClaim, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<CoinClaim, uint> Piece { get; }
        public global::SpacetimeDB.Col<CoinClaim, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<CoinClaim, byte> Seat { get; }
        public global::SpacetimeDB.Col<CoinClaim, byte> Value { get; }

        public CoinClaimCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<CoinClaim, ulong>(tableName, "key");
            RoomId = new global::SpacetimeDB.Col<CoinClaim, ulong>(tableName, "room_id");
            Piece = new global::SpacetimeDB.Col<CoinClaim, uint>(tableName, "piece");
            Owner = new global::SpacetimeDB.Col<CoinClaim, SpacetimeDB.Identity>(tableName, "owner");
            Seat = new global::SpacetimeDB.Col<CoinClaim, byte>(tableName, "seat");
            Value = new global::SpacetimeDB.Col<CoinClaim, byte>(tableName, "value");
        }
    }

    public sealed class CoinClaimIxCols
    {
        public global::SpacetimeDB.IxCol<CoinClaim, ulong> Key { get; }
        public global::SpacetimeDB.IxCol<CoinClaim, ulong> RoomId { get; }

        public CoinClaimIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<CoinClaim, ulong>(tableName, "key");
            RoomId = new global::SpacetimeDB.IxCol<CoinClaim, ulong>(tableName, "room_id");
        }
    }
}
