// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomSeatHandle : RemoteTableHandle<EventContext, RoomSeat>
        {
            public override string RemoteTableName => "room_seat";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RoomSeat row) => row.Id;

                public IdUniqueIndex(RoomSeatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RoomSeat row) => row.RoomId;

                public RoomIdIndex(RoomSeatHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal RoomSeatHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomSeat row) => row.Id;
        }

        public readonly RoomSeatHandle RoomSeat;
    }

    public sealed class RoomSeatCols
    {
        public global::SpacetimeDB.Col<RoomSeat, ulong> Id { get; }
        public global::SpacetimeDB.Col<RoomSeat, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<RoomSeat, byte> Seat { get; }
        public global::SpacetimeDB.Col<RoomSeat, byte> Kind { get; }
        public global::SpacetimeDB.Col<RoomSeat, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<RoomSeat, string> Name { get; }
        public global::SpacetimeDB.Col<RoomSeat, byte> Look { get; }
        public global::SpacetimeDB.Col<RoomSeat, byte> BotLevel { get; }

        public RoomSeatCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<RoomSeat, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.Col<RoomSeat, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<RoomSeat, byte>(tableName, "seat");
            Kind = new global::SpacetimeDB.Col<RoomSeat, byte>(tableName, "kind");
            Player = new global::SpacetimeDB.Col<RoomSeat, SpacetimeDB.Identity>(tableName, "player");
            Name = new global::SpacetimeDB.Col<RoomSeat, string>(tableName, "name");
            Look = new global::SpacetimeDB.Col<RoomSeat, byte>(tableName, "look");
            BotLevel = new global::SpacetimeDB.Col<RoomSeat, byte>(tableName, "bot_level");
        }
    }

    public sealed class RoomSeatIxCols
    {
        public global::SpacetimeDB.IxCol<RoomSeat, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<RoomSeat, ulong> RoomId { get; }

        public RoomSeatIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<RoomSeat, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.IxCol<RoomSeat, ulong>(tableName, "room_id");
        }
    }
}
