// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RunnerStatsHandle : RemoteTableHandle<EventContext, RunnerStats>
        {
            public override string RemoteTableName => "runner_stats";

            public sealed class PlayerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(RunnerStats row) => row.Player;

                public PlayerUniqueIndex(RunnerStatsHandle table) : base(table) { }
            }

            public readonly PlayerUniqueIndex Player;

            internal RunnerStatsHandle(DbConnection conn) : base(conn)
            {
                Player = new(this);
            }

            protected override object GetPrimaryKey(RunnerStats row) => row.Player;
        }

        public readonly RunnerStatsHandle RunnerStats;
    }

    public sealed class RunnerStatsCols
    {
        public global::SpacetimeDB.Col<RunnerStats, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<RunnerStats, uint> Races { get; }
        public global::SpacetimeDB.Col<RunnerStats, uint> Wins { get; }
        public global::SpacetimeDB.Col<RunnerStats, ulong> Coins { get; }
        public global::SpacetimeDB.Col<RunnerStats, uint> BestDistance { get; }
        public global::SpacetimeDB.Col<RunnerStats, long> BestScore { get; }

        public RunnerStatsCols(string tableName)
        {
            Player = new global::SpacetimeDB.Col<RunnerStats, SpacetimeDB.Identity>(tableName, "player");
            Races = new global::SpacetimeDB.Col<RunnerStats, uint>(tableName, "races");
            Wins = new global::SpacetimeDB.Col<RunnerStats, uint>(tableName, "wins");
            Coins = new global::SpacetimeDB.Col<RunnerStats, ulong>(tableName, "coins");
            BestDistance = new global::SpacetimeDB.Col<RunnerStats, uint>(tableName, "best_distance");
            BestScore = new global::SpacetimeDB.Col<RunnerStats, long>(tableName, "best_score");
        }
    }

    public sealed class RunnerStatsIxCols
    {
        public global::SpacetimeDB.IxCol<RunnerStats, SpacetimeDB.Identity> Player { get; }

        public RunnerStatsIxCols(string tableName)
        {
            Player = new global::SpacetimeDB.IxCol<RunnerStats, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
