// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearRoomSaveHandler(ReducerEventContext ctx);
        public event ClearRoomSaveHandler? OnClearRoomSave;

        public void ClearRoomSave()
        {
            conn.InternalCallReducer(new Reducer.ClearRoomSave());
        }

        public bool InvokeClearRoomSave(ReducerEventContext ctx, Reducer.ClearRoomSave args)
        {
            if (OnClearRoomSave == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearRoomSave(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearRoomSave : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "clear_room_save";
        }
    }
}
