// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FinishPlayingHandler(ReducerEventContext ctx, long score);
        public event FinishPlayingHandler? OnFinishPlaying;

        public void FinishPlaying(long score)
        {
            conn.InternalCallReducer(new Reducer.FinishPlaying(score));
        }

        public bool InvokeFinishPlaying(ReducerEventContext ctx, Reducer.FinishPlaying args)
        {
            if (OnFinishPlaying == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFinishPlaying(
                ctx,
                args.Score
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FinishPlaying : Reducer, IReducerArgs
        {
            [DataMember(Name = "score")]
            public long Score;

            public FinishPlaying(long Score)
            {
                this.Score = Score;
            }

            public FinishPlaying()
            {
            }

            string IReducerArgs.ReducerName => "finish_playing";
        }
    }
}
