// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FlipCardHandler(ReducerEventContext ctx, ushort index);
        public event FlipCardHandler? OnFlipCard;

        public void FlipCard(ushort index)
        {
            conn.InternalCallReducer(new Reducer.FlipCard(index));
        }

        public bool InvokeFlipCard(ReducerEventContext ctx, Reducer.FlipCard args)
        {
            if (OnFlipCard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFlipCard(
                ctx,
                args.Index
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FlipCard : Reducer, IReducerArgs
        {
            [DataMember(Name = "index")]
            public ushort Index;

            public FlipCard(ushort Index)
            {
                this.Index = Index;
            }

            public FlipCard()
            {
            }

            string IReducerArgs.ReducerName => "flip_card";
        }
    }
}
