// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportScoreHandler(ReducerEventContext ctx, long score);
        public event ReportScoreHandler? OnReportScore;

        public void ReportScore(long score)
        {
            conn.InternalCallReducer(new Reducer.ReportScore(score));
        }

        public bool InvokeReportScore(ReducerEventContext ctx, Reducer.ReportScore args)
        {
            if (OnReportScore == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportScore(
                ctx,
                args.Score
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportScore : Reducer, IReducerArgs
        {
            [DataMember(Name = "score")]
            public long Score;

            public ReportScore(long Score)
            {
                this.Score = Score;
            }

            public ReportScore()
            {
            }

            string IReducerArgs.ReducerName => "report_score";
        }
    }
}
