// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CoinClaim
    {
        [DataMember(Name = "key")]
        public ulong Key;
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "piece")]
        public uint Piece;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "value")]
        public byte Value;

        public CoinClaim(
            ulong Key,
            ulong RoomId,
            uint Piece,
            SpacetimeDB.Identity Owner,
            byte Seat,
            byte Value
        )
        {
            this.Key = Key;
            this.RoomId = RoomId;
            this.Piece = Piece;
            this.Owner = Owner;
            this.Seat = Seat;
            this.Value = Value;
        }

        public CoinClaim()
        {
        }
    }
}
