// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomPose
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "z")]
        public float Z;
        [DataMember(Name = "velocity_x")]
        public float VelocityX;
        [DataMember(Name = "velocity_y")]
        public float VelocityY;
        [DataMember(Name = "velocity_z")]
        public float VelocityZ;
        [DataMember(Name = "heading")]
        public float Heading;
        [DataMember(Name = "state")]
        public uint State;
        [DataMember(Name = "value")]
        public int Value;
        [DataMember(Name = "sequence")]
        public uint Sequence;

        public RoomPose(
            SpacetimeDB.Identity Identity,
            ulong RoomId,
            float X,
            float Y,
            float Z,
            float VelocityX,
            float VelocityY,
            float VelocityZ,
            float Heading,
            uint State,
            int Value,
            uint Sequence
        )
        {
            this.Identity = Identity;
            this.RoomId = RoomId;
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            this.VelocityX = VelocityX;
            this.VelocityY = VelocityY;
            this.VelocityZ = VelocityZ;
            this.Heading = Heading;
            this.State = State;
            this.Value = Value;
            this.Sequence = Sequence;
        }

        public RoomPose()
        {
        }
    }
}
