// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomAction
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "kind")]
        public uint Kind;
        [DataMember(Name = "payload")]
        public string Payload;
        [DataMember(Name = "random")]
        public uint Random;
        [DataMember(Name = "at")]
        public SpacetimeDB.Timestamp At;

        public RoomAction(
            ulong Id,
            ulong RoomId,
            SpacetimeDB.Identity Sender,
            byte Seat,
            uint Kind,
            string Payload,
            uint Random,
            SpacetimeDB.Timestamp At
        )
        {
            this.Id = Id;
            this.RoomId = RoomId;
            this.Sender = Sender;
            this.Seat = Seat;
            this.Kind = Kind;
            this.Payload = Payload;
            this.Random = Random;
            this.At = At;
        }

        public RoomAction()
        {
            this.Payload = "";
        }
    }
}
