// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RunnerStats
    {
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "races")]
        public uint Races;
        [DataMember(Name = "wins")]
        public uint Wins;
        [DataMember(Name = "coins")]
        public ulong Coins;
        [DataMember(Name = "best_distance")]
        public uint BestDistance;
        [DataMember(Name = "best_score")]
        public long BestScore;

        public RunnerStats(
            SpacetimeDB.Identity Player,
            uint Races,
            uint Wins,
            ulong Coins,
            uint BestDistance,
            long BestScore
        )
        {
            this.Player = Player;
            this.Races = Races;
            this.Wins = Wins;
            this.Coins = Coins;
            this.BestDistance = BestDistance;
            this.BestScore = BestScore;
        }

        public RunnerStats()
        {
        }
    }
}
