// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RunnerRace
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "length")]
        public uint Length;
        [DataMember(Name = "track_coins")]
        public uint TrackCoins;
        [DataMember(Name = "claimed_coins")]
        public uint ClaimedCoins;

        public RunnerRace(
            ulong RoomId,
            int Level,
            uint Length,
            uint TrackCoins,
            uint ClaimedCoins
        )
        {
            this.RoomId = RoomId;
            this.Level = Level;
            this.Length = Length;
            this.TrackCoins = TrackCoins;
            this.ClaimedCoins = ClaimedCoins;
        }

        public RunnerRace()
        {
        }
    }
}
