// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Session
    {
        [DataMember(Name = "connection_id")]
        public SpacetimeDB.ConnectionId ConnectionId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "connected_at")]
        public SpacetimeDB.Timestamp ConnectedAt;

        public Session(
            SpacetimeDB.ConnectionId ConnectionId,
            SpacetimeDB.Identity Identity,
            SpacetimeDB.Timestamp ConnectedAt
        )
        {
            this.ConnectionId = ConnectionId;
            this.Identity = Identity;
            this.ConnectedAt = ConnectedAt;
        }

        public Session()
        {
        }
    }
}
