// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class HeroesStatsHandle : RemoteTableHandle<EventContext, HeroesStats>
        {
            public override string RemoteTableName => "heroes_stats";

            public sealed class PlayerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(HeroesStats row) => row.Player;

                public PlayerUniqueIndex(HeroesStatsHandle table) : base(table) { }
            }

            public readonly PlayerUniqueIndex Player;

            internal HeroesStatsHandle(DbConnection conn) : base(conn)
            {
                Player = new(this);
            }

            protected override object GetPrimaryKey(HeroesStats row) => row.Player;
        }

        public readonly HeroesStatsHandle HeroesStats;
    }

    public sealed class HeroesStatsCols
    {
        public global::SpacetimeDB.Col<HeroesStats, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<HeroesStats, uint> Games { get; }
        public global::SpacetimeDB.Col<HeroesStats, uint> Wins { get; }
        public global::SpacetimeDB.Col<HeroesStats, long> BestRealm { get; }

        public HeroesStatsCols(string tableName)
        {
            Player = new global::SpacetimeDB.Col<HeroesStats, SpacetimeDB.Identity>(tableName, "player");
            Games = new global::SpacetimeDB.Col<HeroesStats, uint>(tableName, "games");
            Wins = new global::SpacetimeDB.Col<HeroesStats, uint>(tableName, "wins");
            BestRealm = new global::SpacetimeDB.Col<HeroesStats, long>(tableName, "best_realm");
        }
    }

    public sealed class HeroesStatsIxCols
    {
        public global::SpacetimeDB.IxCol<HeroesStats, SpacetimeDB.Identity> Player { get; }

        public HeroesStatsIxCols(string tableName)
        {
            Player = new global::SpacetimeDB.IxCol<HeroesStats, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
