// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class HeroesSeatHandle : RemoteTableHandle<EventContext, HeroesSeat>
        {
            public override string RemoteTableName => "heroes_seat";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(HeroesSeat row) => row.Id;

                public IdUniqueIndex(HeroesSeatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(HeroesSeat row) => row.RoomId;

                public RoomIdIndex(HeroesSeatHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal HeroesSeatHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(HeroesSeat row) => row.Id;
        }

        public readonly HeroesSeatHandle HeroesSeat;
    }

    public sealed class HeroesSeatCols
    {
        public global::SpacetimeDB.Col<HeroesSeat, ulong> Id { get; }
        public global::SpacetimeDB.Col<HeroesSeat, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<HeroesSeat, byte> Seat { get; }
        public global::SpacetimeDB.Col<HeroesSeat, byte> Kind { get; }
        public global::SpacetimeDB.Col<HeroesSeat, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<HeroesSeat, string> Name { get; }
        public global::SpacetimeDB.Col<HeroesSeat, byte> Faction { get; }
        public global::SpacetimeDB.Col<HeroesSeat, byte> BotLevel { get; }

        public HeroesSeatCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<HeroesSeat, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.Col<HeroesSeat, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<HeroesSeat, byte>(tableName, "seat");
            Kind = new global::SpacetimeDB.Col<HeroesSeat, byte>(tableName, "kind");
            Player = new global::SpacetimeDB.Col<HeroesSeat, SpacetimeDB.Identity>(tableName, "player");
            Name = new global::SpacetimeDB.Col<HeroesSeat, string>(tableName, "name");
            Faction = new global::SpacetimeDB.Col<HeroesSeat, byte>(tableName, "faction");
            BotLevel = new global::SpacetimeDB.Col<HeroesSeat, byte>(tableName, "bot_level");
        }
    }

    public sealed class HeroesSeatIxCols
    {
        public global::SpacetimeDB.IxCol<HeroesSeat, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<HeroesSeat, ulong> RoomId { get; }

        public HeroesSeatIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<HeroesSeat, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.IxCol<HeroesSeat, ulong>(tableName, "room_id");
        }
    }
}
