// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomMemberHandle : RemoteTableHandle<EventContext, RoomMember>
        {
            public override string RemoteTableName => "room_member";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(RoomMember row) => row.Identity;

                public IdentityUniqueIndex(RoomMemberHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RoomMember row) => row.RoomId;

                public RoomIdIndex(RoomMemberHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal RoomMemberHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomMember row) => row.Identity;
        }

        public readonly RoomMemberHandle RoomMember;
    }

    public sealed class RoomMemberCols
    {
        public global::SpacetimeDB.Col<RoomMember, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<RoomMember, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<RoomMember, byte> Seat { get; }
        public global::SpacetimeDB.Col<RoomMember, bool> Ready { get; }
        public global::SpacetimeDB.Col<RoomMember, bool> Playing { get; }
        public global::SpacetimeDB.Col<RoomMember, long> Score { get; }
        public global::SpacetimeDB.Col<RoomMember, uint> Place { get; }
        public global::SpacetimeDB.Col<RoomMember, SpacetimeDB.Timestamp> JoinedAt { get; }

        public RoomMemberCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<RoomMember, SpacetimeDB.Identity>(tableName, "identity");
            RoomId = new global::SpacetimeDB.Col<RoomMember, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<RoomMember, byte>(tableName, "seat");
            Ready = new global::SpacetimeDB.Col<RoomMember, bool>(tableName, "ready");
            Playing = new global::SpacetimeDB.Col<RoomMember, bool>(tableName, "playing");
            Score = new global::SpacetimeDB.Col<RoomMember, long>(tableName, "score");
            Place = new global::SpacetimeDB.Col<RoomMember, uint>(tableName, "place");
            JoinedAt = new global::SpacetimeDB.Col<RoomMember, SpacetimeDB.Timestamp>(tableName, "joined_at");
        }
    }

    public sealed class RoomMemberIxCols
    {
        public global::SpacetimeDB.IxCol<RoomMember, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<RoomMember, ulong> RoomId { get; }

        public RoomMemberIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<RoomMember, SpacetimeDB.Identity>(tableName, "identity");
            RoomId = new global::SpacetimeDB.IxCol<RoomMember, ulong>(tableName, "room_id");
        }
    }
}
