// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class UserHandle : RemoteTableHandle<EventContext, User>
        {
            public override string RemoteTableName => "user";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(User row) => row.Identity;

                public IdentityUniqueIndex(UserHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UserHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(User row) => row.Identity;
        }

        public readonly UserHandle User;
    }

    public sealed class UserCols
    {
        public global::SpacetimeDB.Col<User, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<User, string> Name { get; }
        public global::SpacetimeDB.Col<User, bool> Guest { get; }
        public global::SpacetimeDB.Col<User, uint> Avatar { get; }
        public global::SpacetimeDB.Col<User, bool> Online { get; }
        public global::SpacetimeDB.Col<User, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<User, SpacetimeDB.Timestamp> LastLoginAt { get; }
        public global::SpacetimeDB.Col<User, SpacetimeDB.Timestamp> LastSeenAt { get; }
        public global::SpacetimeDB.Col<User, uint> Logins { get; }
        public global::SpacetimeDB.Col<User, ulong> SecondsOnline { get; }

        public UserCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<User, SpacetimeDB.Identity>(tableName, "identity");
            Name = new global::SpacetimeDB.Col<User, string>(tableName, "name");
            Guest = new global::SpacetimeDB.Col<User, bool>(tableName, "guest");
            Avatar = new global::SpacetimeDB.Col<User, uint>(tableName, "avatar");
            Online = new global::SpacetimeDB.Col<User, bool>(tableName, "online");
            CreatedAt = new global::SpacetimeDB.Col<User, SpacetimeDB.Timestamp>(tableName, "created_at");
            LastLoginAt = new global::SpacetimeDB.Col<User, SpacetimeDB.Timestamp>(tableName, "last_login_at");
            LastSeenAt = new global::SpacetimeDB.Col<User, SpacetimeDB.Timestamp>(tableName, "last_seen_at");
            Logins = new global::SpacetimeDB.Col<User, uint>(tableName, "logins");
            SecondsOnline = new global::SpacetimeDB.Col<User, ulong>(tableName, "seconds_online");
        }
    }

    public sealed class UserIxCols
    {
        public global::SpacetimeDB.IxCol<User, SpacetimeDB.Identity> Identity { get; }

        public UserIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<User, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
