// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BodyGone
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "exits")]
        public System.Collections.Generic.List<BodyExit> Exits;

        public BodyGone(
            ulong RoomId,
            System.Collections.Generic.List<BodyExit> Exits
        )
        {
            this.RoomId = RoomId;
            this.Exits = Exits;
        }

        public BodyGone()
        {
            this.Exits = new();
        }
    }
}
