// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BodyExit
    {
        [DataMember(Name = "net_id")]
        public uint NetId;
        [DataMember(Name = "reason")]
        public byte Reason;
        [DataMember(Name = "seat")]
        public byte Seat;

        public BodyExit(
            uint NetId,
            byte Reason,
            byte Seat
        )
        {
            this.NetId = NetId;
            this.Reason = Reason;
            this.Seat = Seat;
        }

        public BodyExit()
        {
        }
    }
}
