// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BodyMove
    {
        [DataMember(Name = "net_id")]
        public uint NetId;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "velocity_x")]
        public float VelocityX;
        [DataMember(Name = "velocity_y")]
        public float VelocityY;
        [DataMember(Name = "heading")]
        public float Heading;
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "flags")]
        public uint Flags;

        public BodyMove(
            uint NetId,
            float X,
            float Y,
            float VelocityX,
            float VelocityY,
            float Heading,
            float Health,
            uint Flags
        )
        {
            this.NetId = NetId;
            this.X = X;
            this.Y = Y;
            this.VelocityX = VelocityX;
            this.VelocityY = VelocityY;
            this.Heading = Heading;
            this.Health = Health;
            this.Flags = Flags;
        }

        public BodyMove()
        {
        }
    }
}
