// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BodySpawn
    {
        [DataMember(Name = "net_id")]
        public uint NetId;
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "variant")]
        public int Variant;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "velocity_x")]
        public float VelocityX;
        [DataMember(Name = "velocity_y")]
        public float VelocityY;
        [DataMember(Name = "heading")]
        public float Heading;
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "timer")]
        public float Timer;
        [DataMember(Name = "flags")]
        public uint Flags;

        public BodySpawn(
            uint NetId,
            byte Kind,
            int Variant,
            float X,
            float Y,
            float VelocityX,
            float VelocityY,
            float Heading,
            float Health,
            float Timer,
            uint Flags
        )
        {
            this.NetId = NetId;
            this.Kind = Kind;
            this.Variant = Variant;
            this.X = X;
            this.Y = Y;
            this.VelocityX = VelocityX;
            this.VelocityY = VelocityY;
            this.Heading = Heading;
            this.Health = Health;
            this.Timer = Timer;
            this.Flags = Flags;
        }

        public BodySpawn()
        {
        }
    }
}
