// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FieldSignals
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "signals")]
        public System.Collections.Generic.List<FieldSignal> Signals;

        public FieldSignals(
            ulong RoomId,
            System.Collections.Generic.List<FieldSignal> Signals
        )
        {
            this.RoomId = RoomId;
            this.Signals = Signals;
        }

        public FieldSignals()
        {
            this.Signals = new();
        }
    }
}
