// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FieldSignal
    {
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "direction_x")]
        public float DirectionX;
        [DataMember(Name = "direction_y")]
        public float DirectionY;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "damage")]
        public float Damage;
        [DataMember(Name = "push")]
        public float Push;
        [DataMember(Name = "color")]
        public uint Color;

        public FieldSignal(
            byte Kind,
            float X,
            float Y,
            float DirectionX,
            float DirectionY,
            float Radius,
            float Damage,
            float Push,
            uint Color
        )
        {
            this.Kind = Kind;
            this.X = X;
            this.Y = Y;
            this.DirectionX = DirectionX;
            this.DirectionY = DirectionY;
            this.Radius = Radius;
            this.Damage = Damage;
            this.Push = Push;
            this.Color = Color;
        }

        public FieldSignal()
        {
        }
    }
}
