// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HitInfo
    {
        [DataMember(Name = "net_id")]
        public uint NetId;
        [DataMember(Name = "amount")]
        public float Amount;
        [DataMember(Name = "direction_x")]
        public float DirectionX;
        [DataMember(Name = "direction_y")]
        public float DirectionY;
        [DataMember(Name = "point_x")]
        public float PointX;
        [DataMember(Name = "point_y")]
        public float PointY;
        [DataMember(Name = "source")]
        public byte Source;

        public HitInfo(
            uint NetId,
            float Amount,
            float DirectionX,
            float DirectionY,
            float PointX,
            float PointY,
            byte Source
        )
        {
            this.NetId = NetId;
            this.Amount = Amount;
            this.DirectionX = DirectionX;
            this.DirectionY = DirectionY;
            this.PointX = PointX;
            this.PointY = PointY;
            this.Source = Source;
        }

        public HitInfo()
        {
        }
    }
}
