// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Mission
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "simulator")]
        public SpacetimeDB.Identity Simulator;
        [DataMember(Name = "half_width")]
        public float HalfWidth;
        [DataMember(Name = "half_height")]
        public float HalfHeight;
        [DataMember(Name = "lives")]
        public uint Lives;
        [DataMember(Name = "wave")]
        public uint Wave;
        [DataMember(Name = "waves_cleared")]
        public uint WavesCleared;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "progress")]
        public float Progress;
        [DataMember(Name = "outcome")]
        public byte Outcome;

        public Mission(
            ulong RoomId,
            int Level,
            SpacetimeDB.Identity Simulator,
            float HalfWidth,
            float HalfHeight,
            uint Lives,
            uint Wave,
            uint WavesCleared,
            string Status,
            float Progress,
            byte Outcome
        )
        {
            this.RoomId = RoomId;
            this.Level = Level;
            this.Simulator = Simulator;
            this.HalfWidth = HalfWidth;
            this.HalfHeight = HalfHeight;
            this.Lives = Lives;
            this.Wave = Wave;
            this.WavesCleared = WavesCleared;
            this.Status = Status;
            this.Progress = Progress;
            this.Outcome = Outcome;
        }

        public Mission()
        {
            this.Status = "";
        }
    }
}
