// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PilotStats
    {
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "missions")]
        public uint Missions;
        [DataMember(Name = "victories")]
        public uint Victories;
        [DataMember(Name = "best_score")]
        public long BestScore;

        public PilotStats(
            SpacetimeDB.Identity Player,
            uint Missions,
            uint Victories,
            long BestScore
        )
        {
            this.Player = Player;
            this.Missions = Missions;
            this.Victories = Victories;
            this.BestScore = BestScore;
        }

        public PilotStats()
        {
        }
    }
}
