// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomTurn
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "number")]
        public uint Number;
        [DataMember(Name = "seconds")]
        public uint Seconds;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp StartedAt;
        [DataMember(Name = "ends_at")]
        public SpacetimeDB.Timestamp EndsAt;

        public RoomTurn(
            ulong RoomId,
            byte Seat,
            uint Number,
            uint Seconds,
            SpacetimeDB.Timestamp StartedAt,
            SpacetimeDB.Timestamp EndsAt
        )
        {
            this.RoomId = RoomId;
            this.Seat = Seat;
            this.Number = Number;
            this.Seconds = Seconds;
            this.StartedAt = StartedAt;
            this.EndsAt = EndsAt;
        }

        public RoomTurn()
        {
        }
    }
}
