// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomSave
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "data")]
        public string Data;
        [DataMember(Name = "seats")]
        public System.Collections.Generic.List<SavedSeat> Seats;
        [DataMember(Name = "at")]
        public SpacetimeDB.Timestamp At;

        public RoomSave(
            ulong RoomId,
            string Name,
            int Level,
            string Data,
            System.Collections.Generic.List<SavedSeat> Seats,
            SpacetimeDB.Timestamp At
        )
        {
            this.RoomId = RoomId;
            this.Name = Name;
            this.Level = Level;
            this.Data = Data;
            this.Seats = Seats;
            this.At = At;
        }

        public RoomSave()
        {
            this.Name = "";
            this.Data = "";
            this.Seats = new();
        }
    }
}
