// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipSignal
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "a")]
        public float A;
        [DataMember(Name = "b")]
        public float B;

        public ShipSignal(
            ulong RoomId,
            byte Seat,
            byte Kind,
            float X,
            float Y,
            float A,
            float B
        )
        {
            this.RoomId = RoomId;
            this.Seat = Seat;
            this.Kind = Kind;
            this.X = X;
            this.Y = Y;
            this.A = A;
            this.B = B;
        }

        public ShipSignal()
        {
        }
    }
}
