// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShotInfo
    {
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "level")]
        public byte Level;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "velocity_x")]
        public float VelocityX;
        [DataMember(Name = "velocity_y")]
        public float VelocityY;
        [DataMember(Name = "lifetime")]
        public float Lifetime;

        public ShotInfo(
            byte Kind,
            byte Level,
            float X,
            float Y,
            float VelocityX,
            float VelocityY,
            float Lifetime
        )
        {
            this.Kind = Kind;
            this.Level = Level;
            this.X = X;
            this.Y = Y;
            this.VelocityX = VelocityX;
            this.VelocityY = VelocityY;
            this.Lifetime = Lifetime;
        }

        public ShotInfo()
        {
        }
    }
}
