// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShotVolley
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "shots")]
        public System.Collections.Generic.List<ShotInfo> Shots;

        public ShotVolley(
            ulong RoomId,
            byte Seat,
            System.Collections.Generic.List<ShotInfo> Shots
        )
        {
            this.RoomId = RoomId;
            this.Seat = Seat;
            this.Shots = Shots;
        }

        public ShotVolley()
        {
            this.Shots = new();
        }
    }
}
