// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BoardCard
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "index")]
        public ushort Index;
        [DataMember(Name = "state")]
        public byte State;
        [DataMember(Name = "frozen")]
        public bool Frozen;
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "animal")]
        public int Animal;
        [DataMember(Name = "matched_by")]
        public byte MatchedBy;

        public BoardCard(
            ulong Id,
            ulong RoomId,
            ushort Index,
            byte State,
            bool Frozen,
            byte Kind,
            int Animal,
            byte MatchedBy
        )
        {
            this.Id = Id;
            this.RoomId = RoomId;
            this.Index = Index;
            this.State = State;
            this.Frozen = Frozen;
            this.Kind = Kind;
            this.Animal = Animal;
            this.MatchedBy = MatchedBy;
        }

        public BoardCard()
        {
        }
    }
}
