// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CardDeck
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "kinds")]
        public System.Collections.Generic.List<byte> Kinds;
        [DataMember(Name = "animals")]
        public System.Collections.Generic.List<int> Animals;

        public CardDeck(
            ulong RoomId,
            System.Collections.Generic.List<byte> Kinds,
            System.Collections.Generic.List<int> Animals
        )
        {
            this.RoomId = RoomId;
            this.Kinds = Kinds;
            this.Animals = Animals;
        }

        public CardDeck()
        {
            this.Kinds = new();
            this.Animals = new();
        }
    }
}
