// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FlipEvent
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "card")]
        public ushort Card;
        [DataMember(Name = "outcome")]
        public byte Outcome;
        [DataMember(Name = "points")]
        public int Points;
        [DataMember(Name = "combo")]
        public uint Combo;
        [DataMember(Name = "cards")]
        public System.Collections.Generic.List<ushort> Cards;
        [DataMember(Name = "kinds")]
        public System.Collections.Generic.List<byte> Kinds;
        [DataMember(Name = "animals")]
        public System.Collections.Generic.List<int> Animals;

        public FlipEvent(
            ulong RoomId,
            byte Seat,
            ushort Card,
            byte Outcome,
            int Points,
            uint Combo,
            System.Collections.Generic.List<ushort> Cards,
            System.Collections.Generic.List<byte> Kinds,
            System.Collections.Generic.List<int> Animals
        )
        {
            this.RoomId = RoomId;
            this.Seat = Seat;
            this.Card = Card;
            this.Outcome = Outcome;
            this.Points = Points;
            this.Combo = Combo;
            this.Cards = Cards;
            this.Kinds = Kinds;
            this.Animals = Animals;
        }

        public FlipEvent()
        {
            this.Cards = new();
            this.Kinds = new();
            this.Animals = new();
        }
    }
}
