// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MemoryBoard
    {
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "cards")]
        public ushort Cards;
        [DataMember(Name = "columns")]
        public byte Columns;
        [DataMember(Name = "match_size")]
        public byte MatchSize;
        [DataMember(Name = "sets")]
        public ushort Sets;
        [DataMember(Name = "matched_sets")]
        public ushort MatchedSets;
        [DataMember(Name = "preview_seconds")]
        public float PreviewSeconds;
        [DataMember(Name = "combo")]
        public uint Combo;
        [DataMember(Name = "mismatch_showing")]
        public bool MismatchShowing;
        [DataMember(Name = "flips")]
        public uint Flips;

        public MemoryBoard(
            ulong RoomId,
            ushort Cards,
            byte Columns,
            byte MatchSize,
            ushort Sets,
            ushort MatchedSets,
            float PreviewSeconds,
            uint Combo,
            bool MismatchShowing,
            uint Flips
        )
        {
            this.RoomId = RoomId;
            this.Cards = Cards;
            this.Columns = Columns;
            this.MatchSize = MatchSize;
            this.Sets = Sets;
            this.MatchedSets = MatchedSets;
            this.PreviewSeconds = PreviewSeconds;
            this.Combo = Combo;
            this.MismatchShowing = MismatchShowing;
            this.Flips = Flips;
        }

        public MemoryBoard()
        {
        }
    }
}
