// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MemoryStats
    {
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "games")]
        public uint Games;
        [DataMember(Name = "wins")]
        public uint Wins;
        [DataMember(Name = "sets")]
        public uint Sets;
        [DataMember(Name = "best_score")]
        public long BestScore;

        public MemoryStats(
            SpacetimeDB.Identity Player,
            uint Games,
            uint Wins,
            uint Sets,
            long BestScore
        )
        {
            this.Player = Player;
            this.Games = Games;
            this.Wins = Wins;
            this.Sets = Sets;
            this.BestScore = BestScore;
        }

        public MemoryStats()
        {
        }
    }
}
