// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomSeat
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "look")]
        public byte Look;
        [DataMember(Name = "bot_level")]
        public byte BotLevel;

        public RoomSeat(
            ulong Id,
            ulong RoomId,
            byte Seat,
            byte Kind,
            SpacetimeDB.Identity Player,
            string Name,
            byte Look,
            byte BotLevel
        )
        {
            this.Id = Id;
            this.RoomId = RoomId;
            this.Seat = Seat;
            this.Kind = Kind;
            this.Player = Player;
            this.Name = Name;
            this.Look = Look;
            this.BotLevel = BotLevel;
        }

        public RoomSeat()
        {
            this.Name = "";
        }
    }
}
