// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    public enum RoomState
    {
        Lobby,
        Playing,
        Finished,
    }
}
