// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Room
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "host")]
        public SpacetimeDB.Identity Host;
        [DataMember(Name = "state")]
        public RoomState State;
        [DataMember(Name = "min_players")]
        public byte MinPlayers;
        [DataMember(Name = "max_players")]
        public byte MaxPlayers;
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "options")]
        public string Options;
        [DataMember(Name = "turn_seconds")]
        public uint TurnSeconds;
        [DataMember(Name = "seed")]
        public uint Seed;
        [DataMember(Name = "round")]
        public uint Round;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp StartedAt;

        public Room(
            ulong Id,
            string Name,
            SpacetimeDB.Identity Host,
            RoomState State,
            byte MinPlayers,
            byte MaxPlayers,
            int Level,
            string Options,
            uint TurnSeconds,
            uint Seed,
            uint Round,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp StartedAt
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Host = Host;
            this.State = State;
            this.MinPlayers = MinPlayers;
            this.MaxPlayers = MaxPlayers;
            this.Level = Level;
            this.Options = Options;
            this.TurnSeconds = TurnSeconds;
            this.Seed = Seed;
            this.Round = Round;
            this.CreatedAt = CreatedAt;
            this.StartedAt = StartedAt;
        }

        public Room()
        {
            this.Name = "";
            this.Options = "";
        }
    }
}
