// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomMember
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "seat")]
        public byte Seat;
        [DataMember(Name = "ready")]
        public bool Ready;
        [DataMember(Name = "playing")]
        public bool Playing;
        [DataMember(Name = "score")]
        public long Score;
        [DataMember(Name = "place")]
        public uint Place;
        [DataMember(Name = "joined_at")]
        public SpacetimeDB.Timestamp JoinedAt;

        public RoomMember(
            SpacetimeDB.Identity Identity,
            ulong RoomId,
            byte Seat,
            bool Ready,
            bool Playing,
            long Score,
            uint Place,
            SpacetimeDB.Timestamp JoinedAt
        )
        {
            this.Identity = Identity;
            this.RoomId = RoomId;
            this.Seat = Seat;
            this.Ready = Ready;
            this.Playing = Playing;
            this.Score = Score;
            this.Place = Place;
            this.JoinedAt = JoinedAt;
        }

        public RoomMember()
        {
        }
    }
}
