// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Monopoly.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class MonopolySeatHandle : RemoteTableHandle<EventContext, MonopolySeat>
        {
            public override string RemoteTableName => "monopoly_seat";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MonopolySeat row) => row.Id;

                public IdUniqueIndex(MonopolySeatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(MonopolySeat row) => row.RoomId;

                public RoomIdIndex(MonopolySeatHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal MonopolySeatHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(MonopolySeat row) => row.Id;
        }

        public readonly MonopolySeatHandle MonopolySeat;
    }

    public sealed class MonopolySeatCols
    {
        public global::SpacetimeDB.Col<MonopolySeat, ulong> Id { get; }
        public global::SpacetimeDB.Col<MonopolySeat, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<MonopolySeat, byte> Seat { get; }
        public global::SpacetimeDB.Col<MonopolySeat, byte> Kind { get; }
        public global::SpacetimeDB.Col<MonopolySeat, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<MonopolySeat, string> Name { get; }
        public global::SpacetimeDB.Col<MonopolySeat, byte> Token { get; }
        public global::SpacetimeDB.Col<MonopolySeat, byte> BotLevel { get; }

        public MonopolySeatCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MonopolySeat, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.Col<MonopolySeat, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<MonopolySeat, byte>(tableName, "seat");
            Kind = new global::SpacetimeDB.Col<MonopolySeat, byte>(tableName, "kind");
            Player = new global::SpacetimeDB.Col<MonopolySeat, SpacetimeDB.Identity>(tableName, "player");
            Name = new global::SpacetimeDB.Col<MonopolySeat, string>(tableName, "name");
            Token = new global::SpacetimeDB.Col<MonopolySeat, byte>(tableName, "token");
            BotLevel = new global::SpacetimeDB.Col<MonopolySeat, byte>(tableName, "bot_level");
        }
    }

    public sealed class MonopolySeatIxCols
    {
        public global::SpacetimeDB.IxCol<MonopolySeat, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<MonopolySeat, ulong> RoomId { get; }

        public MonopolySeatIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MonopolySeat, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.IxCol<MonopolySeat, ulong>(tableName, "room_id");
        }
    }
}
