// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Monopoly.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class MonopolyStatsHandle : RemoteTableHandle<EventContext, MonopolyStats>
        {
            public override string RemoteTableName => "monopoly_stats";

            public sealed class PlayerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(MonopolyStats row) => row.Player;

                public PlayerUniqueIndex(MonopolyStatsHandle table) : base(table) { }
            }

            public readonly PlayerUniqueIndex Player;

            internal MonopolyStatsHandle(DbConnection conn) : base(conn)
            {
                Player = new(this);
            }

            protected override object GetPrimaryKey(MonopolyStats row) => row.Player;
        }

        public readonly MonopolyStatsHandle MonopolyStats;
    }

    public sealed class MonopolyStatsCols
    {
        public global::SpacetimeDB.Col<MonopolyStats, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<MonopolyStats, uint> Games { get; }
        public global::SpacetimeDB.Col<MonopolyStats, uint> Wins { get; }
        public global::SpacetimeDB.Col<MonopolyStats, long> BestNetWorth { get; }

        public MonopolyStatsCols(string tableName)
        {
            Player = new global::SpacetimeDB.Col<MonopolyStats, SpacetimeDB.Identity>(tableName, "player");
            Games = new global::SpacetimeDB.Col<MonopolyStats, uint>(tableName, "games");
            Wins = new global::SpacetimeDB.Col<MonopolyStats, uint>(tableName, "wins");
            BestNetWorth = new global::SpacetimeDB.Col<MonopolyStats, long>(tableName, "best_net_worth");
        }
    }

    public sealed class MonopolyStatsIxCols
    {
        public global::SpacetimeDB.IxCol<MonopolyStats, SpacetimeDB.Identity> Player { get; }

        public MonopolyStatsIxCols(string tableName)
        {
            Player = new global::SpacetimeDB.IxCol<MonopolyStats, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
