// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Monopoly.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomActionHandle : RemoteTableHandle<EventContext, RoomAction>
        {
            public override string RemoteTableName => "room_action";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RoomAction row) => row.Id;

                public IdUniqueIndex(RoomActionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RoomAction row) => row.RoomId;

                public RoomIdIndex(RoomActionHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal RoomActionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomAction row) => row.Id;
        }

        public readonly RoomActionHandle RoomAction;
    }

    public sealed class RoomActionCols
    {
        public global::SpacetimeDB.Col<RoomAction, ulong> Id { get; }
        public global::SpacetimeDB.Col<RoomAction, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<RoomAction, SpacetimeDB.Identity> Sender { get; }
        public global::SpacetimeDB.Col<RoomAction, byte> Seat { get; }
        public global::SpacetimeDB.Col<RoomAction, uint> Kind { get; }
        public global::SpacetimeDB.Col<RoomAction, string> Payload { get; }
        public global::SpacetimeDB.Col<RoomAction, uint> Random { get; }
        public global::SpacetimeDB.Col<RoomAction, SpacetimeDB.Timestamp> At { get; }

        public RoomActionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<RoomAction, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.Col<RoomAction, ulong>(tableName, "room_id");
            Sender = new global::SpacetimeDB.Col<RoomAction, SpacetimeDB.Identity>(tableName, "sender");
            Seat = new global::SpacetimeDB.Col<RoomAction, byte>(tableName, "seat");
            Kind = new global::SpacetimeDB.Col<RoomAction, uint>(tableName, "kind");
            Payload = new global::SpacetimeDB.Col<RoomAction, string>(tableName, "payload");
            Random = new global::SpacetimeDB.Col<RoomAction, uint>(tableName, "random");
            At = new global::SpacetimeDB.Col<RoomAction, SpacetimeDB.Timestamp>(tableName, "at");
        }
    }

    public sealed class RoomActionIxCols
    {
        public global::SpacetimeDB.IxCol<RoomAction, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<RoomAction, ulong> RoomId { get; }

        public RoomActionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<RoomAction, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.IxCol<RoomAction, ulong>(tableName, "room_id");
        }
    }
}
