// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HeroesStats
    {
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "games")]
        public uint Games;
        [DataMember(Name = "wins")]
        public uint Wins;
        [DataMember(Name = "best_realm")]
        public long BestRealm;

        public HeroesStats(
            SpacetimeDB.Identity Player,
            uint Games,
            uint Wins,
            long BestRealm
        )
        {
            this.Player = Player;
            this.Games = Games;
            this.Wins = Wins;
            this.BestRealm = BestRealm;
        }

        public HeroesStats()
        {
        }
    }
}
