// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SavedSeat
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "look")]
        public byte Look;
        [DataMember(Name = "bot_level")]
        public byte BotLevel;

        public SavedSeat(
            string Name,
            byte Kind,
            byte Look,
            byte BotLevel
        )
        {
            this.Name = Name;
            this.Kind = Kind;
            this.Look = Look;
            this.BotLevel = BotLevel;
        }

        public SavedSeat()
        {
            this.Name = "";
        }
    }
}
