// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TurnTimer
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "room_id")]
        public ulong RoomId;
        [DataMember(Name = "turn_number")]
        public uint TurnNumber;

        public TurnTimer(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            ulong RoomId,
            uint TurnNumber
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduledAt = ScheduledAt;
            this.RoomId = RoomId;
            this.TurnNumber = TurnNumber;
        }

        public TurnTimer()
        {
            this.ScheduledAt = null!;
        }
    }
}
