// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserName
    {
        [DataMember(Name = "key")]
        public string Key;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;

        public UserName(
            string Key,
            SpacetimeDB.Identity Owner
        )
        {
            this.Key = Key;
            this.Owner = Owner;
        }

        public UserName()
        {
            this.Key = "";
        }
    }
}
