// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimBodyHandler(ReducerEventContext ctx, uint netId);
        public event ClaimBodyHandler? OnClaimBody;

        public void ClaimBody(uint netId)
        {
            conn.InternalCallReducer(new Reducer.ClaimBody(netId));
        }

        public bool InvokeClaimBody(ReducerEventContext ctx, Reducer.ClaimBody args)
        {
            if (OnClaimBody == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimBody(
                ctx,
                args.NetId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimBody : Reducer, IReducerArgs
        {
            [DataMember(Name = "net_id")]
            public uint NetId;

            public ClaimBody(uint NetId)
            {
                this.NetId = NetId;
            }

            public ClaimBody()
            {
            }

            string IReducerArgs.ReducerName => "claim_body";
        }
    }
}
