// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateRoomHandler(ReducerEventContext ctx, string name, byte maxPlayers, int level, string options);
        public event CreateRoomHandler? OnCreateRoom;

        public void CreateRoom(string name, byte maxPlayers, int level, string options)
        {
            conn.InternalCallReducer(new Reducer.CreateRoom(name, maxPlayers, level, options));
        }

        public bool InvokeCreateRoom(ReducerEventContext ctx, Reducer.CreateRoom args)
        {
            if (OnCreateRoom == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateRoom(
                ctx,
                args.Name,
                args.MaxPlayers,
                args.Level,
                args.Options
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateRoom : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "max_players")]
            public byte MaxPlayers;
            [DataMember(Name = "level")]
            public int Level;
            [DataMember(Name = "options")]
            public string Options;

            public CreateRoom(
                string Name,
                byte MaxPlayers,
                int Level,
                string Options
            )
            {
                this.Name = Name;
                this.MaxPlayers = MaxPlayers;
                this.Level = Level;
                this.Options = Options;
            }

            public CreateRoom()
            {
                this.Name = "";
                this.Options = "";
            }

            string IReducerArgs.ReducerName => "create_room";
        }
    }
}
