// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FireShotsHandler(ReducerEventContext ctx, System.Collections.Generic.List<Portfolio.Asteroids.Server.ShotInfo> shots);
        public event FireShotsHandler? OnFireShots;

        public void FireShots(System.Collections.Generic.List<Portfolio.Asteroids.Server.ShotInfo> shots)
        {
            conn.InternalCallReducer(new Reducer.FireShots(shots));
        }

        public bool InvokeFireShots(ReducerEventContext ctx, Reducer.FireShots args)
        {
            if (OnFireShots == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFireShots(
                ctx,
                args.Shots
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FireShots : Reducer, IReducerArgs
        {
            [DataMember(Name = "shots")]
            public System.Collections.Generic.List<ShotInfo> Shots;

            public FireShots(System.Collections.Generic.List<ShotInfo> Shots)
            {
                this.Shots = Shots;
            }

            public FireShots()
            {
                this.Shots = new();
            }

            string IReducerArgs.ReducerName => "fire_shots";
        }
    }
}
