// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportMissionHandler(ReducerEventContext ctx, uint wave, uint wavesCleared, string status, float progress);
        public event ReportMissionHandler? OnReportMission;

        public void ReportMission(uint wave, uint wavesCleared, string status, float progress)
        {
            conn.InternalCallReducer(new Reducer.ReportMission(wave, wavesCleared, status, progress));
        }

        public bool InvokeReportMission(ReducerEventContext ctx, Reducer.ReportMission args)
        {
            if (OnReportMission == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportMission(
                ctx,
                args.Wave,
                args.WavesCleared,
                args.Status,
                args.Progress
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportMission : Reducer, IReducerArgs
        {
            [DataMember(Name = "wave")]
            public uint Wave;
            [DataMember(Name = "waves_cleared")]
            public uint WavesCleared;
            [DataMember(Name = "status")]
            public string Status;
            [DataMember(Name = "progress")]
            public float Progress;

            public ReportMission(
                uint Wave,
                uint WavesCleared,
                string Status,
                float Progress
            )
            {
                this.Wave = Wave;
                this.WavesCleared = WavesCleared;
                this.Status = Status;
                this.Progress = Progress;
            }

            public ReportMission()
            {
                this.Status = "";
            }

            string IReducerArgs.ReducerName => "report_mission";
        }
    }
}
