// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportHitsHandler(ReducerEventContext ctx, System.Collections.Generic.List<Portfolio.Asteroids.Server.HitInfo> hits);
        public event ReportHitsHandler? OnReportHits;

        public void ReportHits(System.Collections.Generic.List<Portfolio.Asteroids.Server.HitInfo> hits)
        {
            conn.InternalCallReducer(new Reducer.ReportHits(hits));
        }

        public bool InvokeReportHits(ReducerEventContext ctx, Reducer.ReportHits args)
        {
            if (OnReportHits == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportHits(
                ctx,
                args.Hits
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportHits : Reducer, IReducerArgs
        {
            [DataMember(Name = "hits")]
            public System.Collections.Generic.List<HitInfo> Hits;

            public ReportHits(System.Collections.Generic.List<HitInfo> Hits)
            {
                this.Hits = Hits;
            }

            public ReportHits()
            {
                this.Hits = new();
            }

            string IReducerArgs.ReducerName => "report_hits";
        }
    }
}
