// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetAvatarHandler(ReducerEventContext ctx, uint avatar);
        public event SetAvatarHandler? OnSetAvatar;

        public void SetAvatar(uint avatar)
        {
            conn.InternalCallReducer(new Reducer.SetAvatar(avatar));
        }

        public bool InvokeSetAvatar(ReducerEventContext ctx, Reducer.SetAvatar args)
        {
            if (OnSetAvatar == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetAvatar(
                ctx,
                args.Avatar
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetAvatar : Reducer, IReducerArgs
        {
            [DataMember(Name = "avatar")]
            public uint Avatar;

            public SetAvatar(uint Avatar)
            {
                this.Avatar = Avatar;
            }

            public SetAvatar()
            {
            }

            string IReducerArgs.ReducerName => "set_avatar";
        }
    }
}
