// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SignalShipHandler(ReducerEventContext ctx, byte kind, float x, float y, float a, float b);
        public event SignalShipHandler? OnSignalShip;

        public void SignalShip(byte kind, float x, float y, float a, float b)
        {
            conn.InternalCallReducer(new Reducer.SignalShip(kind, x, y, a, b));
        }

        public bool InvokeSignalShip(ReducerEventContext ctx, Reducer.SignalShip args)
        {
            if (OnSignalShip == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSignalShip(
                ctx,
                args.Kind,
                args.X,
                args.Y,
                args.A,
                args.B
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SignalShip : Reducer, IReducerArgs
        {
            [DataMember(Name = "kind")]
            public byte Kind;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "a")]
            public float A;
            [DataMember(Name = "b")]
            public float B;

            public SignalShip(
                byte Kind,
                float X,
                float Y,
                float A,
                float B
            )
            {
                this.Kind = Kind;
                this.X = X;
                this.Y = Y;
                this.A = A;
                this.B = B;
            }

            public SignalShip()
            {
            }

            string IReducerArgs.ReducerName => "signal_ship";
        }
    }
}
