// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SubmitActionHandler(ReducerEventContext ctx, byte seat, uint kind, string payload);
        public event SubmitActionHandler? OnSubmitAction;

        public void SubmitAction(byte seat, uint kind, string payload)
        {
            conn.InternalCallReducer(new Reducer.SubmitAction(seat, kind, payload));
        }

        public bool InvokeSubmitAction(ReducerEventContext ctx, Reducer.SubmitAction args)
        {
            if (OnSubmitAction == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSubmitAction(
                ctx,
                args.Seat,
                args.Kind,
                args.Payload
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SubmitAction : Reducer, IReducerArgs
        {
            [DataMember(Name = "seat")]
            public byte Seat;
            [DataMember(Name = "kind")]
            public uint Kind;
            [DataMember(Name = "payload")]
            public string Payload;

            public SubmitAction(
                byte Seat,
                uint Kind,
                string Payload
            )
            {
                this.Seat = Seat;
                this.Kind = Kind;
                this.Payload = Payload;
            }

            public SubmitAction()
            {
                this.Payload = "";
            }

            string IReducerArgs.ReducerName => "submit_action";
        }
    }
}
