// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SyncFieldHandler(ReducerEventContext ctx, System.Collections.Generic.List<Portfolio.Asteroids.Server.BodySpawn> spawns, System.Collections.Generic.List<Portfolio.Asteroids.Server.BodyMove> moves, System.Collections.Generic.List<Portfolio.Asteroids.Server.BodyExit> exits, System.Collections.Generic.List<Portfolio.Asteroids.Server.FieldSignal> signals);
        public event SyncFieldHandler? OnSyncField;

        public void SyncField(System.Collections.Generic.List<Portfolio.Asteroids.Server.BodySpawn> spawns, System.Collections.Generic.List<Portfolio.Asteroids.Server.BodyMove> moves, System.Collections.Generic.List<Portfolio.Asteroids.Server.BodyExit> exits, System.Collections.Generic.List<Portfolio.Asteroids.Server.FieldSignal> signals)
        {
            conn.InternalCallReducer(new Reducer.SyncField(spawns, moves, exits, signals));
        }

        public bool InvokeSyncField(ReducerEventContext ctx, Reducer.SyncField args)
        {
            if (OnSyncField == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSyncField(
                ctx,
                args.Spawns,
                args.Moves,
                args.Exits,
                args.Signals
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SyncField : Reducer, IReducerArgs
        {
            [DataMember(Name = "spawns")]
            public System.Collections.Generic.List<BodySpawn> Spawns;
            [DataMember(Name = "moves")]
            public System.Collections.Generic.List<BodyMove> Moves;
            [DataMember(Name = "exits")]
            public System.Collections.Generic.List<BodyExit> Exits;
            [DataMember(Name = "signals")]
            public System.Collections.Generic.List<FieldSignal> Signals;

            public SyncField(
                System.Collections.Generic.List<BodySpawn> Spawns,
                System.Collections.Generic.List<BodyMove> Moves,
                System.Collections.Generic.List<BodyExit> Exits,
                System.Collections.Generic.List<FieldSignal> Signals
            )
            {
                this.Spawns = Spawns;
                this.Moves = Moves;
                this.Exits = Exits;
                this.Signals = Signals;
            }

            public SyncField()
            {
                this.Spawns = new();
                this.Moves = new();
                this.Exits = new();
                this.Signals = new();
            }

            string IReducerArgs.ReducerName => "sync_field";
        }
    }
}
