// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinRoomHandler(ReducerEventContext ctx, ulong roomId);
        public event JoinRoomHandler? OnJoinRoom;

        public void JoinRoom(ulong roomId)
        {
            conn.InternalCallReducer(new Reducer.JoinRoom(roomId));
        }

        public bool InvokeJoinRoom(ReducerEventContext ctx, Reducer.JoinRoom args)
        {
            if (OnJoinRoom == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinRoom(
                ctx,
                args.RoomId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinRoom : Reducer, IReducerArgs
        {
            [DataMember(Name = "room_id")]
            public ulong RoomId;

            public JoinRoom(ulong RoomId)
            {
                this.RoomId = RoomId;
            }

            public JoinRoom()
            {
            }

            string IReducerArgs.ReducerName => "join_room";
        }
    }
}
