// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LeaveRoomHandler(ReducerEventContext ctx);
        public event LeaveRoomHandler? OnLeaveRoom;

        public void LeaveRoom()
        {
            conn.InternalCallReducer(new Reducer.LeaveRoom());
        }

        public bool InvokeLeaveRoom(ReducerEventContext ctx, Reducer.LeaveRoom args)
        {
            if (OnLeaveRoom == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLeaveRoom(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LeaveRoom : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "leave_room";
        }
    }
}
