// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetRoomSaveHandler(ReducerEventContext ctx, string name, int level, string data, System.Collections.Generic.List<Portfolio.Heroes.Server.SavedSeat> seats);
        public event SetRoomSaveHandler? OnSetRoomSave;

        public void SetRoomSave(string name, int level, string data, System.Collections.Generic.List<Portfolio.Heroes.Server.SavedSeat> seats)
        {
            conn.InternalCallReducer(new Reducer.SetRoomSave(name, level, data, seats));
        }

        public bool InvokeSetRoomSave(ReducerEventContext ctx, Reducer.SetRoomSave args)
        {
            if (OnSetRoomSave == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetRoomSave(
                ctx,
                args.Name,
                args.Level,
                args.Data,
                args.Seats
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetRoomSave : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "level")]
            public int Level;
            [DataMember(Name = "data")]
            public string Data;
            [DataMember(Name = "seats")]
            public System.Collections.Generic.List<SavedSeat> Seats;

            public SetRoomSave(
                string Name,
                int Level,
                string Data,
                System.Collections.Generic.List<SavedSeat> Seats
            )
            {
                this.Name = Name;
                this.Level = Level;
                this.Data = Data;
                this.Seats = Seats;
            }

            public SetRoomSave()
            {
                this.Name = "";
                this.Data = "";
                this.Seats = new();
            }

            string IReducerArgs.ReducerName => "set_room_save";
        }
    }
}
