// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartRoomHandler(ReducerEventContext ctx);
        public event StartRoomHandler? OnStartRoom;

        public void StartRoom()
        {
            conn.InternalCallReducer(new Reducer.StartRoom());
        }

        public bool InvokeStartRoom(ReducerEventContext ctx, Reducer.StartRoom args)
        {
            if (OnStartRoom == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartRoom(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartRoom : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "start_room";
        }
    }
}
