// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Heroes.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePoseHandler(ReducerEventContext ctx, float x, float y, float z, float velocityX, float velocityY, float velocityZ, float heading, uint state, int value);
        public event UpdatePoseHandler? OnUpdatePose;

        public void UpdatePose(float x, float y, float z, float velocityX, float velocityY, float velocityZ, float heading, uint state, int value)
        {
            conn.InternalCallReducer(new Reducer.UpdatePose(x, y, z, velocityX, velocityY, velocityZ, heading, state, value));
        }

        public bool InvokeUpdatePose(ReducerEventContext ctx, Reducer.UpdatePose args)
        {
            if (OnUpdatePose == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePose(
                ctx,
                args.X,
                args.Y,
                args.Z,
                args.VelocityX,
                args.VelocityY,
                args.VelocityZ,
                args.Heading,
                args.State,
                args.Value
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePose : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "velocity_x")]
            public float VelocityX;
            [DataMember(Name = "velocity_y")]
            public float VelocityY;
            [DataMember(Name = "velocity_z")]
            public float VelocityZ;
            [DataMember(Name = "heading")]
            public float Heading;
            [DataMember(Name = "state")]
            public uint State;
            [DataMember(Name = "value")]
            public int Value;

            public UpdatePose(
                float X,
                float Y,
                float Z,
                float VelocityX,
                float VelocityY,
                float VelocityZ,
                float Heading,
                uint State,
                int Value
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.VelocityX = VelocityX;
                this.VelocityY = VelocityY;
                this.VelocityZ = VelocityZ;
                this.Heading = Heading;
                this.State = State;
                this.Value = Value;
            }

            public UpdatePose()
            {
            }

            string IReducerArgs.ReducerName => "update_pose";
        }
    }
}
