// Generated by Gamebox > Server > Generate Client Bindings from GameServerClient.cs of BaseGame.
// Derive from this class to add to it: the file is written again with every generation.

using System;
using Gamebox.Online;
using UnityEngine;

namespace Portfolio.Heroes.Server
{
    /// <summary>
    /// The server client of the bindings next to this file: the component to put in a scene. It ties the shared
    /// <see cref="ServerClient"/> to the tables and the reducers of the base server as these bindings name them
    /// (users, rooms and their members, turns, the action log, the seats of a table, poses), which is all that has to
    /// be written per set of bindings; everything else, the same whatever the names, is in the base classes.
    ///
    /// The original of this class belongs to BaseGame's bindings of the base server;
    /// <c>Gamebox &gt; Server &gt; Generate Client Bindings</c> and <c>Publish All Games</c> write it into a game, in the
    /// namespace of the game's bindings. So change the original, keep what is not tied to generated names in the base
    /// classes, and add a game's own tables and reducers in a class derived from this one, or from outside through
    /// <c>Connection</c> and <c>ConnectionOpened</c>.
    /// </summary>
    [AddComponentMenu("Gamebox/Online/Game Server Client (Portfolio.Heroes.Server)")]
    public class GameServerClient : ServerClient<DbConnection, RemoteTables, Reducer>
    {
        protected override void Bind(DbConnection connection)
        {
            RemoteTables db = connection.Db;
            Watch(db.User, row => NotifyPlayerChanged(ToProfile(row)), row => NotifyPlayerRemoved(row.Identity));
            Watch(db.Room, row => NotifyRoomChanged(ToRoom(row)), row => NotifyRoomRemoved(row.Id));
            Watch(db.RoomMember, row => NotifyMemberChanged(ToMember(row)), row => NotifyMemberRemoved(row.Identity));
            Watch(db.RoomTurn, row => NotifyTurnChanged(ToTurn(row)), row => NotifyTurnRemoved(row.RoomId));
            Watch(db.RoomSeat, row => NotifySeatChanged(ToSeat(row)), row => NotifySeatRemoved(row.Id));
            Watch(db.RoomPose, row => NotifyPoseChanged(ToPose(row)), row => NotifyPoseRemoved(row.Identity));
            db.RoomAction.OnInsert += (context, row) => NotifyAction(ToAction(row));

            RemoteReducers reducers = connection.Reducers;
            reducers.OnSetName += (context, playerName) => NotifyReducerFinished(SetNameReducer, context.Event.Status);
            reducers.OnSetAvatar += (context, avatar) => NotifyReducerFinished(SetAvatarReducer, context.Event.Status);
            reducers.OnDeleteAccount += context => NotifyReducerFinished(DeleteAccountReducer, context.Event.Status);
            reducers.OnCreateRoom += (context, roomName, maxPlayers, level, options) => NotifyReducerFinished(CreateRoomReducer, context.Event.Status);
            reducers.OnJoinRoom += (context, roomId) => NotifyReducerFinished(JoinRoomReducer, context.Event.Status);
            reducers.OnLeaveRoom += context => NotifyReducerFinished(LeaveRoomReducer, context.Event.Status);
            reducers.OnSetReady += (context, ready) => NotifyReducerFinished(SetReadyReducer, context.Event.Status);
            reducers.OnConfigureRoomGame += (context, maxPlayers, level, options) => NotifyReducerFinished(ConfigureRoomGameReducer, context.Event.Status);
            reducers.OnStartRoom += context => NotifyReducerFinished(StartRoomReducer, context.Event.Status);
            reducers.OnReportScore += (context, score) => NotifyReducerFinished(ReportScoreReducer, context.Event.Status);
            reducers.OnFinishPlaying += (context, score) => NotifyReducerFinished(FinishPlayingReducer, context.Event.Status);
            reducers.OnEndRoom += context => NotifyReducerFinished(EndRoomReducer, context.Event.Status);
            reducers.OnSubmitAction += (context, seat, kind, payload) => NotifyReducerFinished(SubmitActionReducer, context.Event.Status);
            connection.OnUnhandledReducerError += (context, error) => Fail(error.Message);
        }

        protected override Action Subscribe(DbConnection connection, string[] queries, Action applied, Action<Exception> failed) =>
            Subscription<SubscriptionEventContext, ErrorContext>(
                (onApplied, onError) => connection.SubscriptionBuilder().OnApplied(onApplied).OnError(onError).Subscribe(queries), applied, failed);

        protected override void SendSetName(string playerName) => Connection.Reducers.SetName(playerName);

        protected override void SendSetAvatar(uint avatar) => Connection.Reducers.SetAvatar(avatar);

        protected override void SendDeleteAccount() => Connection.Reducers.DeleteAccount();

        protected override void SendCreateRoom(string roomName, byte maxPlayers, int level, string options) =>
            Connection.Reducers.CreateRoom(roomName, maxPlayers, level, options);

        protected override void SendJoinRoom(ulong roomId) => Connection.Reducers.JoinRoom(roomId);

        protected override void SendLeaveRoom() => Connection.Reducers.LeaveRoom();

        protected override void SendSetReady(bool ready) => Connection.Reducers.SetReady(ready);

        protected override void SendConfigureRoomGame(byte maxPlayers, int level, string options) =>
            Connection.Reducers.ConfigureRoomGame(maxPlayers, level, options);

        protected override void SendStartRoom() => Connection.Reducers.StartRoom();

        protected override void SendReportScore(long score) => Connection.Reducers.ReportScore(score);

        protected override void SendFinishPlaying(long score) => Connection.Reducers.FinishPlaying(score);

        protected override void SendEndRoom() => Connection.Reducers.EndRoom();

        protected override void SendSubmitAction(byte seat, uint kind, string payload) => Connection.Reducers.SubmitAction(seat, kind, payload);

        protected override void SendUpdatePose(Vector3 position, Vector3 velocity, float heading, uint state, int value) =>
            Connection.Reducers.UpdatePose(position.x, position.y, position.z, velocity.x, velocity.y, velocity.z, heading, state, value);

        private static PlayerProfile ToProfile(User row) => new PlayerProfile(row.Identity, row.Name, row.Guest, row.Avatar, row.Online,
            row.CreatedAt, row.LastLoginAt, row.LastSeenAt, row.Logins, row.SecondsOnline);

        private static RoomInfo ToRoom(Room row) => new RoomInfo(row.Id, row.Name, row.Host, (RoomPhase)(int)row.State, row.MinPlayers,
            row.MaxPlayers, row.Level, row.Options, row.TurnSeconds, row.Seed, row.Round);

        private static RoomMemberInfo ToMember(RoomMember row) =>
            new RoomMemberInfo(row.Identity, row.RoomId, row.Seat, row.Ready, row.Playing, row.Score, row.Place);

        private static RoomTurnInfo ToTurn(RoomTurn row) => new RoomTurnInfo(row.RoomId, row.Seat, row.Number, row.Seconds);

        private static RoomActionInfo ToAction(RoomAction row) =>
            new RoomActionInfo(row.Id, row.RoomId, row.Sender, row.Seat, row.Kind, row.Payload, row.Random);

        private static RoomSeatInfo ToSeat(RoomSeat row) =>
            new RoomSeatInfo(row.Id, row.RoomId, row.Seat, row.Kind, row.Player, row.Name, row.Look, row.BotLevel);

        private static RoomPoseInfo ToPose(RoomPose row) => new RoomPoseInfo(row.Identity, row.RoomId, new Vector3(row.X, row.Y, row.Z),
            new Vector3(row.VelocityX, row.VelocityY, row.VelocityZ), row.Heading, row.State, row.Value, row.Sequence);
    }
}
