// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class BodyGoneHandle : RemoteEventTableHandle<EventContext, BodyGone>
        {
            public override string RemoteTableName => "body_gone";

            internal BodyGoneHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly BodyGoneHandle BodyGone;
    }

    public sealed class BodyGoneCols
    {
        public global::SpacetimeDB.Col<BodyGone, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<BodyGone, System.Collections.Generic.List<BodyExit>> Exits { get; }

        public BodyGoneCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<BodyGone, ulong>(tableName, "room_id");
            Exits = new global::SpacetimeDB.Col<BodyGone, System.Collections.Generic.List<BodyExit>>(tableName, "exits");
        }
    }

    public sealed class BodyGoneIxCols
    {

        public BodyGoneIxCols(string tableName)
        {
        }
    }
}
