// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class FieldBodyHandle : RemoteTableHandle<EventContext, FieldBody>
        {
            public override string RemoteTableName => "field_body";

            public sealed class KeyUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(FieldBody row) => row.Key;

                public KeyUniqueIndex(FieldBodyHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(FieldBody row) => row.RoomId;

                public RoomIdIndex(FieldBodyHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal FieldBodyHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(FieldBody row) => row.Key;
        }

        public readonly FieldBodyHandle FieldBody;
    }

    public sealed class FieldBodyCols
    {
        public global::SpacetimeDB.Col<FieldBody, ulong> Key { get; }
        public global::SpacetimeDB.Col<FieldBody, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<FieldBody, uint> NetId { get; }
        public global::SpacetimeDB.Col<FieldBody, byte> Kind { get; }
        public global::SpacetimeDB.Col<FieldBody, int> Variant { get; }
        public global::SpacetimeDB.Col<FieldBody, float> X { get; }
        public global::SpacetimeDB.Col<FieldBody, float> Y { get; }
        public global::SpacetimeDB.Col<FieldBody, float> VelocityX { get; }
        public global::SpacetimeDB.Col<FieldBody, float> VelocityY { get; }
        public global::SpacetimeDB.Col<FieldBody, float> Heading { get; }
        public global::SpacetimeDB.Col<FieldBody, float> Health { get; }
        public global::SpacetimeDB.Col<FieldBody, float> Timer { get; }
        public global::SpacetimeDB.Col<FieldBody, uint> Flags { get; }
        public global::SpacetimeDB.Col<FieldBody, byte> ClaimedBy { get; }

        public FieldBodyCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<FieldBody, ulong>(tableName, "key");
            RoomId = new global::SpacetimeDB.Col<FieldBody, ulong>(tableName, "room_id");
            NetId = new global::SpacetimeDB.Col<FieldBody, uint>(tableName, "net_id");
            Kind = new global::SpacetimeDB.Col<FieldBody, byte>(tableName, "kind");
            Variant = new global::SpacetimeDB.Col<FieldBody, int>(tableName, "variant");
            X = new global::SpacetimeDB.Col<FieldBody, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<FieldBody, float>(tableName, "y");
            VelocityX = new global::SpacetimeDB.Col<FieldBody, float>(tableName, "velocity_x");
            VelocityY = new global::SpacetimeDB.Col<FieldBody, float>(tableName, "velocity_y");
            Heading = new global::SpacetimeDB.Col<FieldBody, float>(tableName, "heading");
            Health = new global::SpacetimeDB.Col<FieldBody, float>(tableName, "health");
            Timer = new global::SpacetimeDB.Col<FieldBody, float>(tableName, "timer");
            Flags = new global::SpacetimeDB.Col<FieldBody, uint>(tableName, "flags");
            ClaimedBy = new global::SpacetimeDB.Col<FieldBody, byte>(tableName, "claimed_by");
        }
    }

    public sealed class FieldBodyIxCols
    {
        public global::SpacetimeDB.IxCol<FieldBody, ulong> Key { get; }
        public global::SpacetimeDB.IxCol<FieldBody, ulong> RoomId { get; }

        public FieldBodyIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<FieldBody, ulong>(tableName, "key");
            RoomId = new global::SpacetimeDB.IxCol<FieldBody, ulong>(tableName, "room_id");
        }
    }
}
