// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class FieldSignalsHandle : RemoteEventTableHandle<EventContext, FieldSignals>
        {
            public override string RemoteTableName => "field_signals";

            internal FieldSignalsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly FieldSignalsHandle FieldSignals;
    }

    public sealed class FieldSignalsCols
    {
        public global::SpacetimeDB.Col<FieldSignals, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<FieldSignals, System.Collections.Generic.List<FieldSignal>> Signals { get; }

        public FieldSignalsCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<FieldSignals, ulong>(tableName, "room_id");
            Signals = new global::SpacetimeDB.Col<FieldSignals, System.Collections.Generic.List<FieldSignal>>(tableName, "signals");
        }
    }

    public sealed class FieldSignalsIxCols
    {

        public FieldSignalsIxCols(string tableName)
        {
        }
    }
}
