// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class HitReportHandle : RemoteEventTableHandle<EventContext, HitReport>
        {
            public override string RemoteTableName => "hit_report";

            internal HitReportHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly HitReportHandle HitReport;
    }

    public sealed class HitReportCols
    {
        public global::SpacetimeDB.Col<HitReport, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<HitReport, byte> Seat { get; }
        public global::SpacetimeDB.Col<HitReport, System.Collections.Generic.List<HitInfo>> Hits { get; }

        public HitReportCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<HitReport, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<HitReport, byte>(tableName, "seat");
            Hits = new global::SpacetimeDB.Col<HitReport, System.Collections.Generic.List<HitInfo>>(tableName, "hits");
        }
    }

    public sealed class HitReportIxCols
    {

        public HitReportIxCols(string tableName)
        {
        }
    }
}
