// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class MissionHandle : RemoteTableHandle<EventContext, Mission>
        {
            public override string RemoteTableName => "mission";

            public sealed class RoomIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Mission row) => row.RoomId;

                public RoomIdUniqueIndex(MissionHandle table) : base(table) { }
            }

            public readonly RoomIdUniqueIndex RoomId;

            internal MissionHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(Mission row) => row.RoomId;
        }

        public readonly MissionHandle Mission;
    }

    public sealed class MissionCols
    {
        public global::SpacetimeDB.Col<Mission, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<Mission, int> Level { get; }
        public global::SpacetimeDB.Col<Mission, SpacetimeDB.Identity> Simulator { get; }
        public global::SpacetimeDB.Col<Mission, float> HalfWidth { get; }
        public global::SpacetimeDB.Col<Mission, float> HalfHeight { get; }
        public global::SpacetimeDB.Col<Mission, uint> Lives { get; }
        public global::SpacetimeDB.Col<Mission, uint> Wave { get; }
        public global::SpacetimeDB.Col<Mission, uint> WavesCleared { get; }
        public global::SpacetimeDB.Col<Mission, string> Status { get; }
        public global::SpacetimeDB.Col<Mission, float> Progress { get; }
        public global::SpacetimeDB.Col<Mission, byte> Outcome { get; }

        public MissionCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<Mission, ulong>(tableName, "room_id");
            Level = new global::SpacetimeDB.Col<Mission, int>(tableName, "level");
            Simulator = new global::SpacetimeDB.Col<Mission, SpacetimeDB.Identity>(tableName, "simulator");
            HalfWidth = new global::SpacetimeDB.Col<Mission, float>(tableName, "half_width");
            HalfHeight = new global::SpacetimeDB.Col<Mission, float>(tableName, "half_height");
            Lives = new global::SpacetimeDB.Col<Mission, uint>(tableName, "lives");
            Wave = new global::SpacetimeDB.Col<Mission, uint>(tableName, "wave");
            WavesCleared = new global::SpacetimeDB.Col<Mission, uint>(tableName, "waves_cleared");
            Status = new global::SpacetimeDB.Col<Mission, string>(tableName, "status");
            Progress = new global::SpacetimeDB.Col<Mission, float>(tableName, "progress");
            Outcome = new global::SpacetimeDB.Col<Mission, byte>(tableName, "outcome");
        }
    }

    public sealed class MissionIxCols
    {
        public global::SpacetimeDB.IxCol<Mission, ulong> RoomId { get; }

        public MissionIxCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.IxCol<Mission, ulong>(tableName, "room_id");
        }
    }
}
