// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class PilotStatsHandle : RemoteTableHandle<EventContext, PilotStats>
        {
            public override string RemoteTableName => "pilot_stats";

            public sealed class PlayerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PilotStats row) => row.Player;

                public PlayerUniqueIndex(PilotStatsHandle table) : base(table) { }
            }

            public readonly PlayerUniqueIndex Player;

            internal PilotStatsHandle(DbConnection conn) : base(conn)
            {
                Player = new(this);
            }

            protected override object GetPrimaryKey(PilotStats row) => row.Player;
        }

        public readonly PilotStatsHandle PilotStats;
    }

    public sealed class PilotStatsCols
    {
        public global::SpacetimeDB.Col<PilotStats, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<PilotStats, uint> Missions { get; }
        public global::SpacetimeDB.Col<PilotStats, uint> Victories { get; }
        public global::SpacetimeDB.Col<PilotStats, long> BestScore { get; }

        public PilotStatsCols(string tableName)
        {
            Player = new global::SpacetimeDB.Col<PilotStats, SpacetimeDB.Identity>(tableName, "player");
            Missions = new global::SpacetimeDB.Col<PilotStats, uint>(tableName, "missions");
            Victories = new global::SpacetimeDB.Col<PilotStats, uint>(tableName, "victories");
            BestScore = new global::SpacetimeDB.Col<PilotStats, long>(tableName, "best_score");
        }
    }

    public sealed class PilotStatsIxCols
    {
        public global::SpacetimeDB.IxCol<PilotStats, SpacetimeDB.Identity> Player { get; }

        public PilotStatsIxCols(string tableName)
        {
            Player = new global::SpacetimeDB.IxCol<PilotStats, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
