// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomPoseHandle : RemoteTableHandle<EventContext, RoomPose>
        {
            public override string RemoteTableName => "room_pose";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(RoomPose row) => row.Identity;

                public IdentityUniqueIndex(RoomPoseHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RoomPose row) => row.RoomId;

                public RoomIdIndex(RoomPoseHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal RoomPoseHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomPose row) => row.Identity;
        }

        public readonly RoomPoseHandle RoomPose;
    }

    public sealed class RoomPoseCols
    {
        public global::SpacetimeDB.Col<RoomPose, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<RoomPose, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<RoomPose, float> X { get; }
        public global::SpacetimeDB.Col<RoomPose, float> Y { get; }
        public global::SpacetimeDB.Col<RoomPose, float> Z { get; }
        public global::SpacetimeDB.Col<RoomPose, float> VelocityX { get; }
        public global::SpacetimeDB.Col<RoomPose, float> VelocityY { get; }
        public global::SpacetimeDB.Col<RoomPose, float> VelocityZ { get; }
        public global::SpacetimeDB.Col<RoomPose, float> Heading { get; }
        public global::SpacetimeDB.Col<RoomPose, uint> State { get; }
        public global::SpacetimeDB.Col<RoomPose, int> Value { get; }
        public global::SpacetimeDB.Col<RoomPose, uint> Sequence { get; }

        public RoomPoseCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<RoomPose, SpacetimeDB.Identity>(tableName, "identity");
            RoomId = new global::SpacetimeDB.Col<RoomPose, ulong>(tableName, "room_id");
            X = new global::SpacetimeDB.Col<RoomPose, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<RoomPose, float>(tableName, "y");
            Z = new global::SpacetimeDB.Col<RoomPose, float>(tableName, "z");
            VelocityX = new global::SpacetimeDB.Col<RoomPose, float>(tableName, "velocity_x");
            VelocityY = new global::SpacetimeDB.Col<RoomPose, float>(tableName, "velocity_y");
            VelocityZ = new global::SpacetimeDB.Col<RoomPose, float>(tableName, "velocity_z");
            Heading = new global::SpacetimeDB.Col<RoomPose, float>(tableName, "heading");
            State = new global::SpacetimeDB.Col<RoomPose, uint>(tableName, "state");
            Value = new global::SpacetimeDB.Col<RoomPose, int>(tableName, "value");
            Sequence = new global::SpacetimeDB.Col<RoomPose, uint>(tableName, "sequence");
        }
    }

    public sealed class RoomPoseIxCols
    {
        public global::SpacetimeDB.IxCol<RoomPose, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<RoomPose, ulong> RoomId { get; }

        public RoomPoseIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<RoomPose, SpacetimeDB.Identity>(tableName, "identity");
            RoomId = new global::SpacetimeDB.IxCol<RoomPose, ulong>(tableName, "room_id");
        }
    }
}
