// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class ShipSignalHandle : RemoteEventTableHandle<EventContext, ShipSignal>
        {
            public override string RemoteTableName => "ship_signal";

            internal ShipSignalHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ShipSignalHandle ShipSignal;
    }

    public sealed class ShipSignalCols
    {
        public global::SpacetimeDB.Col<ShipSignal, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<ShipSignal, byte> Seat { get; }
        public global::SpacetimeDB.Col<ShipSignal, byte> Kind { get; }
        public global::SpacetimeDB.Col<ShipSignal, float> X { get; }
        public global::SpacetimeDB.Col<ShipSignal, float> Y { get; }
        public global::SpacetimeDB.Col<ShipSignal, float> A { get; }
        public global::SpacetimeDB.Col<ShipSignal, float> B { get; }

        public ShipSignalCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<ShipSignal, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<ShipSignal, byte>(tableName, "seat");
            Kind = new global::SpacetimeDB.Col<ShipSignal, byte>(tableName, "kind");
            X = new global::SpacetimeDB.Col<ShipSignal, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<ShipSignal, float>(tableName, "y");
            A = new global::SpacetimeDB.Col<ShipSignal, float>(tableName, "a");
            B = new global::SpacetimeDB.Col<ShipSignal, float>(tableName, "b");
        }
    }

    public sealed class ShipSignalIxCols
    {

        public ShipSignalIxCols(string tableName)
        {
        }
    }
}
