// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Asteroids.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class ShotVolleyHandle : RemoteEventTableHandle<EventContext, ShotVolley>
        {
            public override string RemoteTableName => "shot_volley";

            internal ShotVolleyHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ShotVolleyHandle ShotVolley;
    }

    public sealed class ShotVolleyCols
    {
        public global::SpacetimeDB.Col<ShotVolley, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<ShotVolley, byte> Seat { get; }
        public global::SpacetimeDB.Col<ShotVolley, System.Collections.Generic.List<ShotInfo>> Shots { get; }

        public ShotVolleyCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<ShotVolley, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<ShotVolley, byte>(tableName, "seat");
            Shots = new global::SpacetimeDB.Col<ShotVolley, System.Collections.Generic.List<ShotInfo>>(tableName, "shots");
        }
    }

    public sealed class ShotVolleyIxCols
    {

        public ShotVolleyIxCols(string tableName)
        {
        }
    }
}
