// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Monopoly.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MonopolyStats
    {
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "games")]
        public uint Games;
        [DataMember(Name = "wins")]
        public uint Wins;
        [DataMember(Name = "best_net_worth")]
        public long BestNetWorth;

        public MonopolyStats(
            SpacetimeDB.Identity Player,
            uint Games,
            uint Wins,
            long BestNetWorth
        )
        {
            this.Player = Player;
            this.Games = Games;
            this.Wins = Wins;
            this.BestNetWorth = BestNetWorth;
        }

        public MonopolyStats()
        {
        }
    }
}
