// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.Monopoly.Server
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class User
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "guest")]
        public bool Guest;
        [DataMember(Name = "avatar")]
        public uint Avatar;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "last_login_at")]
        public SpacetimeDB.Timestamp LastLoginAt;
        [DataMember(Name = "last_seen_at")]
        public SpacetimeDB.Timestamp LastSeenAt;
        [DataMember(Name = "logins")]
        public uint Logins;
        [DataMember(Name = "seconds_online")]
        public ulong SecondsOnline;

        public User(
            SpacetimeDB.Identity Identity,
            string Name,
            bool Guest,
            uint Avatar,
            bool Online,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp LastLoginAt,
            SpacetimeDB.Timestamp LastSeenAt,
            uint Logins,
            ulong SecondsOnline
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Guest = Guest;
            this.Avatar = Avatar;
            this.Online = Online;
            this.CreatedAt = CreatedAt;
            this.LastLoginAt = LastLoginAt;
            this.LastSeenAt = LastSeenAt;
            this.Logins = Logins;
            this.SecondsOnline = SecondsOnline;
        }

        public User()
        {
            this.Name = "";
        }
    }
}
