// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimPieceHandler(ReducerEventContext ctx, uint piece, byte value);
        public event ClaimPieceHandler? OnClaimPiece;

        public void ClaimPiece(uint piece, byte value)
        {
            conn.InternalCallReducer(new Reducer.ClaimPiece(piece, value));
        }

        public bool InvokeClaimPiece(ReducerEventContext ctx, Reducer.ClaimPiece args)
        {
            if (OnClaimPiece == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimPiece(
                ctx,
                args.Piece,
                args.Value
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimPiece : Reducer, IReducerArgs
        {
            [DataMember(Name = "piece")]
            public uint Piece;
            [DataMember(Name = "value")]
            public byte Value;

            public ClaimPiece(
                uint Piece,
                byte Value
            )
            {
                this.Piece = Piece;
                this.Value = Value;
            }

            public ClaimPiece()
            {
            }

            string IReducerArgs.ReducerName => "claim_piece";
        }
    }
}
