// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ConfigureRoomGameHandler(ReducerEventContext ctx, byte maxPlayers, int level, string options);
        public event ConfigureRoomGameHandler? OnConfigureRoomGame;

        public void ConfigureRoomGame(byte maxPlayers, int level, string options)
        {
            conn.InternalCallReducer(new Reducer.ConfigureRoomGame(maxPlayers, level, options));
        }

        public bool InvokeConfigureRoomGame(ReducerEventContext ctx, Reducer.ConfigureRoomGame args)
        {
            if (OnConfigureRoomGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnConfigureRoomGame(
                ctx,
                args.MaxPlayers,
                args.Level,
                args.Options
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ConfigureRoomGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "max_players")]
            public byte MaxPlayers;
            [DataMember(Name = "level")]
            public int Level;
            [DataMember(Name = "options")]
            public string Options;

            public ConfigureRoomGame(
                byte MaxPlayers,
                int Level,
                string Options
            )
            {
                this.MaxPlayers = MaxPlayers;
                this.Level = Level;
                this.Options = Options;
            }

            public ConfigureRoomGame()
            {
                this.Options = "";
            }

            string IReducerArgs.ReducerName => "configure_room_game";
        }
    }
}
