// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.EndlessRunner.Server
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FinishRunHandler(ReducerEventContext ctx, uint distance, long score);
        public event FinishRunHandler? OnFinishRun;

        public void FinishRun(uint distance, long score)
        {
            conn.InternalCallReducer(new Reducer.FinishRun(distance, score));
        }

        public bool InvokeFinishRun(ReducerEventContext ctx, Reducer.FinishRun args)
        {
            if (OnFinishRun == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFinishRun(
                ctx,
                args.Distance,
                args.Score
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FinishRun : Reducer, IReducerArgs
        {
            [DataMember(Name = "distance")]
            public uint Distance;
            [DataMember(Name = "score")]
            public long Score;

            public FinishRun(
                uint Distance,
                long Score
            )
            {
                this.Distance = Distance;
                this.Score = Score;
            }

            public FinishRun()
            {
            }

            string IReducerArgs.ReducerName => "finish_run";
        }
    }
}
