// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class BoardCardHandle : RemoteTableHandle<EventContext, BoardCard>
        {
            public override string RemoteTableName => "board_card";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BoardCard row) => row.Id;

                public IdUniqueIndex(BoardCardHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RoomIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(BoardCard row) => row.RoomId;

                public RoomIdIndex(BoardCardHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal BoardCardHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(BoardCard row) => row.Id;
        }

        public readonly BoardCardHandle BoardCard;
    }

    public sealed class BoardCardCols
    {
        public global::SpacetimeDB.Col<BoardCard, ulong> Id { get; }
        public global::SpacetimeDB.Col<BoardCard, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<BoardCard, ushort> Index { get; }
        public global::SpacetimeDB.Col<BoardCard, byte> State { get; }
        public global::SpacetimeDB.Col<BoardCard, bool> Frozen { get; }
        public global::SpacetimeDB.Col<BoardCard, byte> Kind { get; }
        public global::SpacetimeDB.Col<BoardCard, int> Animal { get; }
        public global::SpacetimeDB.Col<BoardCard, byte> MatchedBy { get; }

        public BoardCardCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BoardCard, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.Col<BoardCard, ulong>(tableName, "room_id");
            Index = new global::SpacetimeDB.Col<BoardCard, ushort>(tableName, "index");
            State = new global::SpacetimeDB.Col<BoardCard, byte>(tableName, "state");
            Frozen = new global::SpacetimeDB.Col<BoardCard, bool>(tableName, "frozen");
            Kind = new global::SpacetimeDB.Col<BoardCard, byte>(tableName, "kind");
            Animal = new global::SpacetimeDB.Col<BoardCard, int>(tableName, "animal");
            MatchedBy = new global::SpacetimeDB.Col<BoardCard, byte>(tableName, "matched_by");
        }
    }

    public sealed class BoardCardIxCols
    {
        public global::SpacetimeDB.IxCol<BoardCard, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<BoardCard, ulong> RoomId { get; }

        public BoardCardIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BoardCard, ulong>(tableName, "id");
            RoomId = new global::SpacetimeDB.IxCol<BoardCard, ulong>(tableName, "room_id");
        }
    }
}
