// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class FlipEventHandle : RemoteEventTableHandle<EventContext, FlipEvent>
        {
            public override string RemoteTableName => "flip_event";

            internal FlipEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly FlipEventHandle FlipEvent;
    }

    public sealed class FlipEventCols
    {
        public global::SpacetimeDB.Col<FlipEvent, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<FlipEvent, byte> Seat { get; }
        public global::SpacetimeDB.Col<FlipEvent, ushort> Card { get; }
        public global::SpacetimeDB.Col<FlipEvent, byte> Outcome { get; }
        public global::SpacetimeDB.Col<FlipEvent, int> Points { get; }
        public global::SpacetimeDB.Col<FlipEvent, uint> Combo { get; }
        public global::SpacetimeDB.Col<FlipEvent, System.Collections.Generic.List<ushort>> Cards { get; }
        public global::SpacetimeDB.Col<FlipEvent, System.Collections.Generic.List<byte>> Kinds { get; }
        public global::SpacetimeDB.Col<FlipEvent, System.Collections.Generic.List<int>> Animals { get; }

        public FlipEventCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<FlipEvent, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<FlipEvent, byte>(tableName, "seat");
            Card = new global::SpacetimeDB.Col<FlipEvent, ushort>(tableName, "card");
            Outcome = new global::SpacetimeDB.Col<FlipEvent, byte>(tableName, "outcome");
            Points = new global::SpacetimeDB.Col<FlipEvent, int>(tableName, "points");
            Combo = new global::SpacetimeDB.Col<FlipEvent, uint>(tableName, "combo");
            Cards = new global::SpacetimeDB.Col<FlipEvent, System.Collections.Generic.List<ushort>>(tableName, "cards");
            Kinds = new global::SpacetimeDB.Col<FlipEvent, System.Collections.Generic.List<byte>>(tableName, "kinds");
            Animals = new global::SpacetimeDB.Col<FlipEvent, System.Collections.Generic.List<int>>(tableName, "animals");
        }
    }

    public sealed class FlipEventIxCols
    {

        public FlipEventIxCols(string tableName)
        {
        }
    }
}
