// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class MemoryStatsHandle : RemoteTableHandle<EventContext, MemoryStats>
        {
            public override string RemoteTableName => "memory_stats";

            public sealed class PlayerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(MemoryStats row) => row.Player;

                public PlayerUniqueIndex(MemoryStatsHandle table) : base(table) { }
            }

            public readonly PlayerUniqueIndex Player;

            internal MemoryStatsHandle(DbConnection conn) : base(conn)
            {
                Player = new(this);
            }

            protected override object GetPrimaryKey(MemoryStats row) => row.Player;
        }

        public readonly MemoryStatsHandle MemoryStats;
    }

    public sealed class MemoryStatsCols
    {
        public global::SpacetimeDB.Col<MemoryStats, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<MemoryStats, uint> Games { get; }
        public global::SpacetimeDB.Col<MemoryStats, uint> Wins { get; }
        public global::SpacetimeDB.Col<MemoryStats, uint> Sets { get; }
        public global::SpacetimeDB.Col<MemoryStats, long> BestScore { get; }

        public MemoryStatsCols(string tableName)
        {
            Player = new global::SpacetimeDB.Col<MemoryStats, SpacetimeDB.Identity>(tableName, "player");
            Games = new global::SpacetimeDB.Col<MemoryStats, uint>(tableName, "games");
            Wins = new global::SpacetimeDB.Col<MemoryStats, uint>(tableName, "wins");
            Sets = new global::SpacetimeDB.Col<MemoryStats, uint>(tableName, "sets");
            BestScore = new global::SpacetimeDB.Col<MemoryStats, long>(tableName, "best_score");
        }
    }

    public sealed class MemoryStatsIxCols
    {
        public global::SpacetimeDB.IxCol<MemoryStats, SpacetimeDB.Identity> Player { get; }

        public MemoryStatsIxCols(string tableName)
        {
            Player = new global::SpacetimeDB.IxCol<MemoryStats, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
