// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class MemoryBoardHandle : RemoteTableHandle<EventContext, MemoryBoard>
        {
            public override string RemoteTableName => "memory_board";

            public sealed class RoomIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MemoryBoard row) => row.RoomId;

                public RoomIdUniqueIndex(MemoryBoardHandle table) : base(table) { }
            }

            public readonly RoomIdUniqueIndex RoomId;

            internal MemoryBoardHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(MemoryBoard row) => row.RoomId;
        }

        public readonly MemoryBoardHandle MemoryBoard;
    }

    public sealed class MemoryBoardCols
    {
        public global::SpacetimeDB.Col<MemoryBoard, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<MemoryBoard, ushort> Cards { get; }
        public global::SpacetimeDB.Col<MemoryBoard, byte> Columns { get; }
        public global::SpacetimeDB.Col<MemoryBoard, byte> MatchSize { get; }
        public global::SpacetimeDB.Col<MemoryBoard, ushort> Sets { get; }
        public global::SpacetimeDB.Col<MemoryBoard, ushort> MatchedSets { get; }
        public global::SpacetimeDB.Col<MemoryBoard, float> PreviewSeconds { get; }
        public global::SpacetimeDB.Col<MemoryBoard, uint> Combo { get; }
        public global::SpacetimeDB.Col<MemoryBoard, bool> MismatchShowing { get; }
        public global::SpacetimeDB.Col<MemoryBoard, uint> Flips { get; }

        public MemoryBoardCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<MemoryBoard, ulong>(tableName, "room_id");
            Cards = new global::SpacetimeDB.Col<MemoryBoard, ushort>(tableName, "cards");
            Columns = new global::SpacetimeDB.Col<MemoryBoard, byte>(tableName, "columns");
            MatchSize = new global::SpacetimeDB.Col<MemoryBoard, byte>(tableName, "match_size");
            Sets = new global::SpacetimeDB.Col<MemoryBoard, ushort>(tableName, "sets");
            MatchedSets = new global::SpacetimeDB.Col<MemoryBoard, ushort>(tableName, "matched_sets");
            PreviewSeconds = new global::SpacetimeDB.Col<MemoryBoard, float>(tableName, "preview_seconds");
            Combo = new global::SpacetimeDB.Col<MemoryBoard, uint>(tableName, "combo");
            MismatchShowing = new global::SpacetimeDB.Col<MemoryBoard, bool>(tableName, "mismatch_showing");
            Flips = new global::SpacetimeDB.Col<MemoryBoard, uint>(tableName, "flips");
        }
    }

    public sealed class MemoryBoardIxCols
    {
        public global::SpacetimeDB.IxCol<MemoryBoard, ulong> RoomId { get; }

        public MemoryBoardIxCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.IxCol<MemoryBoard, ulong>(tableName, "room_id");
        }
    }
}
