// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomSaveHandle : RemoteTableHandle<EventContext, RoomSave>
        {
            public override string RemoteTableName => "room_save";

            public sealed class RoomIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RoomSave row) => row.RoomId;

                public RoomIdUniqueIndex(RoomSaveHandle table) : base(table) { }
            }

            public readonly RoomIdUniqueIndex RoomId;

            internal RoomSaveHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomSave row) => row.RoomId;
        }

        public readonly RoomSaveHandle RoomSave;
    }

    public sealed class RoomSaveCols
    {
        public global::SpacetimeDB.Col<RoomSave, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<RoomSave, string> Name { get; }
        public global::SpacetimeDB.Col<RoomSave, int> Level { get; }
        public global::SpacetimeDB.Col<RoomSave, string> Data { get; }
        public global::SpacetimeDB.Col<RoomSave, System.Collections.Generic.List<SavedSeat>> Seats { get; }
        public global::SpacetimeDB.Col<RoomSave, SpacetimeDB.Timestamp> At { get; }

        public RoomSaveCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<RoomSave, ulong>(tableName, "room_id");
            Name = new global::SpacetimeDB.Col<RoomSave, string>(tableName, "name");
            Level = new global::SpacetimeDB.Col<RoomSave, int>(tableName, "level");
            Data = new global::SpacetimeDB.Col<RoomSave, string>(tableName, "data");
            Seats = new global::SpacetimeDB.Col<RoomSave, System.Collections.Generic.List<SavedSeat>>(tableName, "seats");
            At = new global::SpacetimeDB.Col<RoomSave, SpacetimeDB.Timestamp>(tableName, "at");
        }
    }

    public sealed class RoomSaveIxCols
    {
        public global::SpacetimeDB.IxCol<RoomSave, ulong> RoomId { get; }

        public RoomSaveIxCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.IxCol<RoomSave, ulong>(tableName, "room_id");
        }
    }
}
