// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomHandle : RemoteTableHandle<EventContext, Room>
        {
            public override string RemoteTableName => "room";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Room row) => row.Id;

                public IdUniqueIndex(RoomHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal RoomHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Room row) => row.Id;
        }

        public readonly RoomHandle Room;
    }

    public sealed class RoomCols
    {
        public global::SpacetimeDB.Col<Room, ulong> Id { get; }
        public global::SpacetimeDB.Col<Room, string> Name { get; }
        public global::SpacetimeDB.Col<Room, SpacetimeDB.Identity> Host { get; }
        public global::SpacetimeDB.Col<Room, RoomState> State { get; }
        public global::SpacetimeDB.Col<Room, byte> MinPlayers { get; }
        public global::SpacetimeDB.Col<Room, byte> MaxPlayers { get; }
        public global::SpacetimeDB.Col<Room, int> Level { get; }
        public global::SpacetimeDB.Col<Room, string> Options { get; }
        public global::SpacetimeDB.Col<Room, uint> TurnSeconds { get; }
        public global::SpacetimeDB.Col<Room, uint> Seed { get; }
        public global::SpacetimeDB.Col<Room, uint> Round { get; }
        public global::SpacetimeDB.Col<Room, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<Room, SpacetimeDB.Timestamp> StartedAt { get; }

        public RoomCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Room, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<Room, string>(tableName, "name");
            Host = new global::SpacetimeDB.Col<Room, SpacetimeDB.Identity>(tableName, "host");
            State = new global::SpacetimeDB.Col<Room, RoomState>(tableName, "state");
            MinPlayers = new global::SpacetimeDB.Col<Room, byte>(tableName, "min_players");
            MaxPlayers = new global::SpacetimeDB.Col<Room, byte>(tableName, "max_players");
            Level = new global::SpacetimeDB.Col<Room, int>(tableName, "level");
            Options = new global::SpacetimeDB.Col<Room, string>(tableName, "options");
            TurnSeconds = new global::SpacetimeDB.Col<Room, uint>(tableName, "turn_seconds");
            Seed = new global::SpacetimeDB.Col<Room, uint>(tableName, "seed");
            Round = new global::SpacetimeDB.Col<Room, uint>(tableName, "round");
            CreatedAt = new global::SpacetimeDB.Col<Room, SpacetimeDB.Timestamp>(tableName, "created_at");
            StartedAt = new global::SpacetimeDB.Col<Room, SpacetimeDB.Timestamp>(tableName, "started_at");
        }
    }

    public sealed class RoomIxCols
    {
        public global::SpacetimeDB.IxCol<Room, ulong> Id { get; }

        public RoomIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Room, ulong>(tableName, "id");
        }
    }
}
