// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Portfolio.MemoryCards.Server
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomTurnHandle : RemoteTableHandle<EventContext, RoomTurn>
        {
            public override string RemoteTableName => "room_turn";

            public sealed class RoomIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RoomTurn row) => row.RoomId;

                public RoomIdUniqueIndex(RoomTurnHandle table) : base(table) { }
            }

            public readonly RoomIdUniqueIndex RoomId;

            internal RoomTurnHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomTurn row) => row.RoomId;
        }

        public readonly RoomTurnHandle RoomTurn;
    }

    public sealed class RoomTurnCols
    {
        public global::SpacetimeDB.Col<RoomTurn, ulong> RoomId { get; }
        public global::SpacetimeDB.Col<RoomTurn, byte> Seat { get; }
        public global::SpacetimeDB.Col<RoomTurn, uint> Number { get; }
        public global::SpacetimeDB.Col<RoomTurn, uint> Seconds { get; }
        public global::SpacetimeDB.Col<RoomTurn, SpacetimeDB.Timestamp> StartedAt { get; }
        public global::SpacetimeDB.Col<RoomTurn, SpacetimeDB.Timestamp> EndsAt { get; }

        public RoomTurnCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.Col<RoomTurn, ulong>(tableName, "room_id");
            Seat = new global::SpacetimeDB.Col<RoomTurn, byte>(tableName, "seat");
            Number = new global::SpacetimeDB.Col<RoomTurn, uint>(tableName, "number");
            Seconds = new global::SpacetimeDB.Col<RoomTurn, uint>(tableName, "seconds");
            StartedAt = new global::SpacetimeDB.Col<RoomTurn, SpacetimeDB.Timestamp>(tableName, "started_at");
            EndsAt = new global::SpacetimeDB.Col<RoomTurn, SpacetimeDB.Timestamp>(tableName, "ends_at");
        }
    }

    public sealed class RoomTurnIxCols
    {
        public global::SpacetimeDB.IxCol<RoomTurn, ulong> RoomId { get; }

        public RoomTurnIxCols(string tableName)
        {
            RoomId = new global::SpacetimeDB.IxCol<RoomTurn, ulong>(tableName, "room_id");
        }
    }
}
